### ISSUE TITLE
Initial homework review

### ISSUE THREAD

**Issue by NateWr** [MrDwina/Home-work2#1]
Great work Mohammed! You've obviously got some experience with HTML code and are already using floats to set up columns on your site. That's pretty cool. We'll be talking about layout at the class next week.

Since you've got a head start, here is some feedback that can help you improve the HTML and CSS code you write.

**Share classes between items**
In some places, you're using separate CSS classes for similar items. For example, in the HTML code for the [gallery items](https://github.com/MrDwina/Home-work2/blob/master/gallery.html#L42-L58), you're using different classes: `item-1`, `item-2` and `item-3`. Then you repeat these classes [in your CSS code](https://github.com/MrDwina/Home-work2/blob/master/css/stylesheet.css#L218-L242).

Instead of using separate classes for each item, try to use the same class for all three, `item`. This will reduce the amount of code you write in your CSS, because you'll only have to write:

```
.item {
  property: value;
}
```

Instead of:

```
.item-1,
.item-2,
.item-3 {
   property: value;
}
```

Once you remove those classes, you'll encounter some tricky issues with the following CSS code:

```
.gallery .itmes .itme-1,
.gallery .itmes .itme-2{
  margin-right: 3%;
}
```

To assign CSS properties to just some of the items, you'll need to use the `:first-child`, `:last-child` or `nth-child` selectors. Research those selectors and see if you can figure out how to use them so that your grid will work without unique class names for each item.

**Try not to duplicate your primary navigation menu**
I noticed that you've got two sets of links for your primary navigation menu. One is displayed as a dropdown on small screens and the other is displayed only on large screens.

https://github.com/MrDwina/Home-work2/blob/master/index.html#L18-L30

See if you can use the knowledge you've already got to make the same behaviour, but with just one set of nav links instead of two.

Great work and good luck! :+1:

**Comment by MrDwina** [comment]
Yeah, I do it, really it is fun, if are there in things just let me know, please and take a look about what I fingered out.

**Comment by NateWr** [comment]
Great work @MrDwina!
